import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { FooterMain } from "@/components/navigation-footer/footer/footer-main";
import { Header } from "@/components/navigation-footer/navigation/header";
import { ReactLenis } from "@/utils/lenis";
import { MouseFollowerProvider } from "@/components/mouse-follower/mouse-follower-provider";
import { PageTransition } from "./components/page-transition";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={`${poppins.variable} font-poppins antialiased`}>
        <ReactLenis root>
          <MouseFollowerProvider>
            <PageTransition />
            <Header />
            <main className="min-h-screen mt-[10rem]">{children}</main>
            <FooterMain />
          </MouseFollowerProvider>
        </ReactLenis>
      </body>
    </html>
  );
}
