import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { FooterMain } from "@/components/navigation-footer/footer/footer-main";
import { Header } from "@/components/navigation-footer/navigation/header";
import { ReactLenis } from "@/utils/lenis";
import { MouseFollowerInit } from "@/components/mouse-follower/mouse-follower-init";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body className={`${poppins.variable} font-poppins antialiased`}>
          <MouseFollowerInit />
          <Header />
          <main className="min-h-screen ">{children}</main>
          <FooterMain />
        </body>
      </ReactLenis>
    </html>
  );
}
